### ISSUE TITLE
advanture game -- https://github.com/tomBeach/choose_your_own_adventure_js

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/choose_your_own_adventure_js#44]
comfort_levels
  coding -- 5
  submitting pull request -- 2 (still doesn't allow me to do a clean pull request from source repo ?!?!?)
completeness -- 5

https://github.com/tomBeach/choose_your_own_adventure_js

**Comment by RobertAKARobin** [comment]
There's probably just a single command you're missing. Are you using the Github desktop app? If not, I would strongly recommend that.
